modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "birdeye"
version = "${version}"
displayName = "Birdeye"
authors = """mifort, JonMyDude
Discord: https://discord.com/invite/qAEWgpaJrZ
Source: https://github.com/mifort-github/Birdeye
Issues: https://github.com/mifort-github/Birdeye/issues
"""
description = '''
Birdeye is a small addon for Xaero's World Map that adds a smooth animation to the map, giving it a bit of life without touching anything else about how the map works.
'''
logoFile = "assets/birdeye/icon.png"

[[dependencies.birdeye]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[modproperties.birdeye]
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.birdeye]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,1.20.1][1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.birdeye]]
modId = "xaerolib"
mandatory = true
versionRange = "[1.0.42,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.birdeye]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[1.40.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.birdeye]]
modId = "cloth_config"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.birdeye]]
modId = "xaerominimap"
mandatory = false
versionRange = "[25.3.5,)"
ordering = "NONE"
side = "CLIENT"
