# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = net.mifort
archives_name = birdeye
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.116.15+1.21.1
neoforge_version = 21.1.9

xaerominimap_version = 25.3.5
xaeroworldmap_version = 1.40.4
xaerolib_version = 1.0.42

cloth_config_version = 15.0.130

mod_menu_version = 11.0.1
